### PR TITLE
Add configuration option to disable printing of passed unit tests

### PR DESCRIPTION
**Pull request by hummy123**
Hi there.

Thanks for the helpful library - I'm using it for testing in [a very basic and very minimal Vim-like editor](https://github.com/hummy123/shf/blob/main/test/test.sml).

I had just one suggestion, which is adding a configuration option to print only tests that have failed. I have > 100 tests in the file linked above and there's a lot of unnecessary noise in the terminal if all tests are printed.

This pull request implements that configuration option while leaving the default behaviour untouched.

### CODE REVIEW

**Comment by MMagueta** [comment]
I can take a look this week, I am just a bit busy. Thanks for the interest in the project!

Although that's @ratsclub's stuff

**Comment by ratsclub** [comment]
This looks great, thanks @hummy123 !

**Comment by ratsclub** [comment]
@hummy123 I've just added the `StopOnFirstFailure` option to the configuration too. This should stop the test runner when it encounters the first failing test.

**Comment by hummy123** [comment]
> @hummy123 I've just added the `StopOnFirstFailure` option to the configuration too. This should stop the test runner when it encounters the first failing test.

Thanks @ratsclub ! I appreciate the update and you remembering me after a year! 😅

I saw your message a couple of weeks ago, but was locked out of GitHub because issues with the phone I use for 2FA meant that I couldn't log in.

Hope you have a great 2026!

**Pull request merged**
